import Foundation

/// Exports of the RH-1 model: per-part STL, one OBJ+MTL assembly, a bill of
/// materials, the full parameter set (the STEP generator's input) and a
/// general-arrangement drawing. All in millimetres, machine frame.
public enum CADExport {

    public static func slug(_ s: String) -> String {
        let allowed = Set("abcdefghijklmnopqrstuvwxyz0123456789-")
        let lower = s.lowercased().replacingOccurrences(of: " ", with: "-")
            .replacingOccurrences(of: ".", with: "-")
        return String(lower.filter { allowed.contains($0) })
            .replacingOccurrences(of: "--", with: "-")
    }

    // MARK: STL

    public static func writeSTL(_ model: RH1Model, to dir: URL) throws -> Int {
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        for p in model.parts {
            let name = "\(slug(p.assembly))__\(slug(p.name)).stl"
            try STL.writeBinary(p.mesh.soup, to: dir.appendingPathComponent(name))
        }
        return model.parts.count
    }

    // MARK: OBJ + MTL

    public static func writeOBJ(_ model: RH1Model, to url: URL) throws {
        let mtlName = url.deletingPathExtension().lastPathComponent + ".mtl"
        var mtl = "# RH-1 materials — spec §8 finishes\n"
        for m in CADMaterial.allCases {
            let (r, g, b, a) = m.rgba
            mtl += "newmtl \(m.rawValue)\n"
            mtl += String(format: "Kd %.4f %.4f %.4f\n", r, g, b)
            mtl += String(format: "Ks %.3f %.3f %.3f\nNs %.1f\nd %.3f\n",
                          m.specular, m.specular, m.specular, m.shininess, a)
            if m.emission > 0 { mtl += String(format: "Ke %.3f %.3f %.3f\n", r, g, b) }
            mtl += "# \(m.label)\n\n"
        }
        try mtl.write(to: url.deletingLastPathComponent().appendingPathComponent(mtlName),
                      atomically: true, encoding: .utf8)

        var out = "# RH-1 free-standing — generated by fieldc cad export (RSW-1)\n"
        out += "# units: mm; frame: floor z=0, axis z, front +x\n"
        out += "mtllib \(mtlName)\n"
        var base = 1
        var chunk = ""
        chunk.reserveCapacity(1 << 20)
        let handle: FileHandle
        FileManager.default.createFile(atPath: url.path, contents: nil)
        handle = try FileHandle(forWritingTo: url)
        defer { try? handle.close() }
        handle.write(out.data(using: .utf8)!)
        for p in model.parts {
            chunk += "o \(slug(p.assembly))__\(slug(p.name))\nusemtl \(p.material.rawValue)\n"
            for v in p.mesh.vertices {
                chunk += String(format: "v %.4f %.4f %.4f\n", v.x, v.y, v.z)
            }
            for f in p.mesh.faces {
                chunk += "f \(Int(f.x) + base) \(Int(f.y) + base) \(Int(f.z) + base)\n"
            }
            base += p.mesh.vertices.count
            handle.write(chunk.data(using: .utf8)!)
            chunk.removeAll(keepingCapacity: true)
        }
    }

    // MARK: BOM

    public struct BOMRow: Codable, Sendable {
        public var assembly: String
        public var part: String
        public var material: String
        public var register: String
        public var volumeCm3: Double
        public var massKg: Double?
        public var bboxMm: [Double]
        public var triangles: Int
        public var note: String
    }

    public static func bom(_ model: RH1Model) -> [BOMRow] {
        model.parts.map { p in
            let b = p.mesh.bounds
            return BOMRow(assembly: p.assembly, part: p.name, material: p.material.label,
                          register: p.register.rawValue,
                          volumeCm3: (p.volume / 1000 * 100).rounded() / 100,
                          massKg: p.massKg.map { ($0 * 1000).rounded() / 1000 },
                          bboxMm: [b.min.x, b.min.y, b.min.z, b.max.x, b.max.y, b.max.z]
                              .map { ($0 * 10).rounded() / 10 },
                          triangles: p.mesh.triangleCount, note: p.note)
        }
    }

    public static func bomMarkdown(_ model: RH1Model) -> String {
        var s = "# RH-1 bill of materials (generated)\n\n"
        s += "Generated by `fieldc cad bom` from `RH1Design` — edit the design, not this file.\n\n"
        s += "| assembly | part | material | register | volume cm³ | mass kg |\n"
        s += "|---|---|---|---|---:|---:|\n"
        var total = 0.0
        for r in bom(model) {
            let m = r.massKg.map { String(format: "%.3f", $0) } ?? "—"
            total += r.massKg ?? 0
            s += "| \(r.assembly) | \(r.part) | \(r.material) | \(r.register) | "
                + String(format: "%.1f", r.volumeCm3) + " | \(m) |\n"
        }
        s += String(format: "\n**Total (excluding placeholder envelopes): %.2f kg**\n", total)
        return s
    }

    // MARK: parameters (input to the STEP generator)

    public struct Params: Codable, Sendable {
        public var generator = "fieldc cad params (RSW-1)"
        public var units = "mm"
        public var design: RH1Design
        public var faces: [RH1Design.Face]
        public var assemblies: [RH1Design.Assembly]
        public var hornProfileRD: [[Double]]       // (r, depth-behind-plate)
        public var coneProfileRD: [[Double]]
        public var sites: [[Double]]               // x, y, faceR, throatR, subsumed(0/1), index
        public var slotCenterlines: [[[Double]]]   // per arm: [x, y, width]
        public var slotOutlines: [[[Double]]]      // per arm: closed outline [x, y]
        public var provenance: [RH1Design.Provenance]
        public var reconciliation: [RH1Design.Reconciliation]
        public var partVolumesMm3: [String: Double]
    }

    public static func params(_ model: RH1Model) -> Params {
        let d = model.design
        let pat = model.pattern
        var vols: [String: Double] = [:]
        for p in model.parts { vols["\(p.assembly)/\(p.name)"] = p.volume }
        return Params(
            design: d, faces: d.faces, assemblies: d.assemblies,
            hornProfileRD: RH1Model.hornProfile(d).map { [$0.x, $0.y] },
            coneProfileRD: RH1Model.coneProfile(d).map { [$0.x, $0.y] },
            sites: pat.sites.map { [$0.center.x, $0.center.y, $0.faceRadius, $0.throatRadius,
                                   $0.subsumed ? 1 : 0, Double($0.index)] },
            slotCenterlines: zip(pat.slotCenterlines, pat.slotWidths).map { (c, w) in
                zip(c, w).map { [$0.0.x, $0.0.y, $0.1] }
            },
            slotOutlines: pat.slotOutlines.map { $0.map { [$0.x, $0.y] } },
            provenance: d.provenance,
            reconciliation: RH1Design.reconciliation,
            partVolumesMm3: vols)
    }

    public static func writeParams(_ model: RH1Model, to url: URL) throws {
        let enc = JSONEncoder()
        enc.outputFormatting = [.prettyPrinted, .sortedKeys]
        try enc.encode(params(model)).write(to: url)
    }

    // MARK: drawing

    /// General-arrangement drawing: half-section elevation (to scale) plus the
    /// plate face in plan — the same two figures etherworks.io draws, now
    /// generated from the parameters so the site can never disagree with the
    /// model again.
    public static func drawingSVG(_ model: RH1Model) -> String {
        let d = model.design
        let s = 0.42                              // px per mm, elevation
        let W = 1500.0, H = 820.0
        let ox = 330.0, oy = 60.0 + d.overallHeight * s   // floor line
        func X(_ r: Double) -> Double { ox + r * s }
        func Y(_ z: Double) -> Double { oy - z * s }
        var g = ""
        func rect(_ r0: Double, _ r1: Double, _ z0: Double, _ z1: Double,
                  _ cls: String, mirror: Bool = true) {
            for sg in (mirror ? [1.0, -1.0] : [1.0]) {
                let a = X(sg * r0), b = X(sg * r1)
                g += String(format: "<rect class=\"%@\" x=\"%.2f\" y=\"%.2f\" width=\"%.2f\" height=\"%.2f\"/>\n",
                            cls, min(a, b), Y(z1), abs(b - a), (z1 - z0) * s)
            }
        }
        func poly(_ pts: [P2], _ cls: String) {
            for sg in [1.0, -1.0] {
                let p = pts.map { String(format: "%.2f,%.2f", X(sg * $0.x), Y($0.y)) }
                    .joined(separator: " ")
                g += "<polygon class=\"\(cls)\" points=\"\(p)\"/>\n"
            }
        }
        func circle(_ r: Double, _ z: Double, _ rad: Double, _ cls: String) {
            for sg in [1.0, -1.0] {
                g += String(format: "<circle class=\"%@\" cx=\"%.2f\" cy=\"%.2f\" r=\"%.2f\"/>\n",
                            cls, X(sg * r), Y(z), rad * s)
            }
        }
        func label(_ text: String, _ z: Double, _ r: Double = 250) {
            g += String(format: "<line class=\"lead\" x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\"/>",
                        X(r - 20), Y(z), X(300), Y(z))
            g += String(format: "<text x=\"%.1f\" y=\"%.1f\">%@</text>\n", X(306), Y(z) + 4, text)
        }
        let R = d.bodyRadius, Ri = d.shellInnerRadius
        // shells
        rect(Ri, R, d.shellWall, d.lowerBodyTop, "shell")
        rect(0, R, 0, d.shellWall, "shell", mirror: false)
        rect(-R, 0, 0, d.shellWall, "shell", mirror: false)
        rect(Ri, R, d.chamberCeiling, d.overallHeight - d.crownCapThickness, "shell")
        rect(-R, R, d.overallHeight - d.crownCapThickness, d.overallHeight, "shell", mirror: false)
        // glass
        rect(d.rearGlassOD / 2 - d.glassWall, d.rearGlassOD / 2, d.chamberFloor, d.chamberCeiling, "glass")
        // storage liner
        rect(d.storageLinerID / 2, d.storageLinerID / 2 + d.storageLinerWall,
             d.storageFloor, d.storageCeiling, "shell")
        // faces
        for f in d.faces {
            let zlo = min(f.faceZ, f.backZ), zhi = max(f.faceZ, f.backZ)
            rect(d.boreHoleRadius, d.plateRadius, zlo, zhi, "plate")
            rect(d.plateRadius, d.carrierOuterRadius, zlo, zhi, "shell")
            poly(RH1Model.hornProfile(d).map { P2($0.x, f.zBehind($0.y)) }, "ceramic")
            poly(RH1Model.coneProfile(d).map { P2($0.x, f.zBehind($0.y)) }, "copper")
            let pz = min(f.zBehind(d.hornThroatDepth), f.zBehind(d.hornThroatDepth + d.pztThickness))
            rect(d.pztPitchRadius - d.pztDiameter / 2, d.pztPitchRadius + d.pztDiameter / 2,
                 pz, pz + d.pztThickness, "pzt")
            let rz = [f.zBehind(d.rimDepthFrom), f.zBehind(d.rimDepthTo)]
            rect(d.rimInnerRadius, d.rimOuterRadius, rz.min()!, rz.max()!, "fr4")
        }
        for a in d.assemblies {
            circle(d.torusMajorRadius, a.torusZ, d.torusTubeRadius, "torus")
            circle(d.torusMajorRadius, a.torusZ,
                   d.torusTubeRadius + d.windingOuterLayerGap + d.windingWireDiameter / 2, "winding")
        }
        // axis and bore
        g += String(format: "<line class=\"axis\" x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\"/>\n",
                    X(0), Y(-20), X(0), Y(d.overallHeight + 20))
        // labels
        let f = d.faces
        label("top plate — faces down (\(Int(f[0].faceZ)))", f[0].faceZ + 6)
        label("top torus Ø\(Int(d.torusMajorDiameter))/Ø\(Int(d.torusTubeDiameter)) (\(Int(f[0].torusZ)))", f[0].torusZ, 190)
        label("build chamber — Ø\(Int(d.rearGlassOD)) glass × \(Int(d.buildChamberHeight))", (d.chamberFloor + d.chamberCeiling) / 2, 222)
        label("mid plate — faces up (\(Int(f[1].faceZ)))", f[1].faceZ - 6)
        label("middle torus (\(Int(d.middleTorusZ)))", d.middleTorusZ, 190)
        label("mid plate — faces down (\(Int(f[2].faceZ)))", f[2].faceZ + 6)
        label("storage chamber — Ø\(Int(d.storageLinerID)) × \(Int(d.storageChamberHeight.rounded()))", (d.storageFloor + d.storageCeiling) / 2, 204)
        label("storage deck — faces up (\(Int(f[3].faceZ)))", f[3].faceZ - 6)
        label("deck torus (\(Int(f[3].torusZ)))", f[3].torusZ, 190)
        label("base — power · compute · feedstock", 200, 226)
        // dimension lines
        g += String(format: "<line class=\"dim\" x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\"/>", X(-R) - 40, Y(0), X(-R) - 40, Y(d.overallHeight))
        g += String(format: "<text class=\"dimt\" transform=\"rotate(-90 %.1f %.1f)\" x=\"%.1f\" y=\"%.1f\">%d</text>\n", X(-R) - 46, Y(d.overallHeight / 2), X(-R) - 46, Y(d.overallHeight / 2), Int(d.overallHeight))
        g += String(format: "<line class=\"dim\" x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\"/>", X(-R), Y(-30), X(R), Y(-30))
        g += String(format: "<text class=\"dimt\" x=\"%.1f\" y=\"%.1f\">Ø%d</text>\n", X(0) - 18, Y(-30) + 16, Int(d.bodyDiameter))

        // plate face, plan view
        let ps = 0.95, cx = 1160.0, cy = 390.0
        var pv = String(format: "<circle class=\"plate\" cx=\"%.1f\" cy=\"%.1f\" r=\"%.2f\"/>\n", cx, cy, d.plateRadius * ps)
        for o in model.pattern.slotOutlines {
            let p = o.map { String(format: "%.2f,%.2f", cx + $0.x * ps, cy - $0.y * ps) }.joined(separator: " ")
            pv += "<polygon class=\"slot\" points=\"\(p)\"/>\n"
        }
        for site in model.pattern.sites {
            pv += String(format: "<circle class=\"%@\" cx=\"%.2f\" cy=\"%.2f\" r=\"%.2f\"/>\n",
                         site.subsumed ? "subsumed" : "hole", cx + site.center.x * ps,
                         cy - site.center.y * ps, site.faceRadius * ps)
        }
        pv += String(format: "<circle class=\"bore\" cx=\"%.1f\" cy=\"%.1f\" r=\"%.2f\"/>\n", cx, cy, d.boreRadius * ps)
        pv += String(format: "<text x=\"%.1f\" y=\"%.1f\">PLATE FACE, PLAN — %d micro-horns drilled, %d inside slot voids, %d slots</text>\n",
                     cx - 250, cy + d.plateRadius * ps + 30, model.pattern.drilled.count,
                     model.pattern.subsumedCount, d.slotArms)

        let css = """
        text{font:12px ui-monospace,Menlo,monospace;fill:#1d1d1f}
        .dimt{font-size:13px}
        .shell{fill:#cbb994;stroke:#6b5d45;stroke-width:.6}
        .glass{fill:#bfe3dc;stroke:#5d8f88;stroke-width:.6}
        .plate{fill:#3a3d42;stroke:#1b1c1f;stroke-width:.6}
        .ceramic{fill:#eee4cf;stroke:#9c8d6c;stroke-width:.5}
        .copper{fill:#d37b46;stroke:#7c3f1f;stroke-width:.4}
        .pzt{fill:#bfc2c9;stroke:#55585e;stroke-width:.4}
        .fr4{fill:#3f6b4b;stroke:#1f3a28;stroke-width:.4}
        .torus{fill:#2a2826;stroke:#111;stroke-width:.5}
        .winding{fill:none;stroke:#b87333;stroke-width:1.4;stroke-dasharray:3 2}
        .axis{stroke:#888;stroke-width:.8;stroke-dasharray:8 4 2 4}
        .lead{stroke:#999;stroke-width:.6}
        .dim{stroke:#1d1d1f;stroke-width:.8}
        .slot{fill:#f7f5ef;stroke:#b87333;stroke-width:.5}
        .hole{fill:#f7f5ef;stroke:none}
        .subsumed{fill:none;stroke:#b87333;stroke-width:.3;stroke-dasharray:1 1}
        .bore{fill:#f7f5ef;stroke:#1d1d1f;stroke-width:.5}
        """
        return """
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 \(Int(W)) \(Int(H))" width="\(Int(W))" height="\(Int(H))">
        <style>\(css)</style>
        <rect x="0" y="0" width="\(Int(W))" height="\(Int(H))" fill="#f7f5ef"/>
        <text x="24" y="30" style="font-size:15px;font-weight:600">RH-1 FREE-STANDING — GENERAL ARRANGEMENT (generated by fieldc cad drawing from RH1Design)</text>
        <text x="24" y="48">half-section elevation to scale, 1:\(Int((1 / (s * 0.264583)).rounded())) at 96 dpi · mm · floor z = 0</text>
        \(g)
        \(pv)
        </svg>
        """
    }
}
